### ISSUE TITLE
Problemas con Learnyounode

### ISSUE THREAD

**Issue by froi** [nodeschool/puertorico#1]
Alguno de ustedes a tenido problemas con el ejercicio My First I/O?

Cuando ejecuto `learnyounode verify first_io.js` este es el output que obtengo

![screenshot 2014-09-11 15 56 17](https://cloud.githubusercontent.com/assets/1918027/4240750/df90b9fa-39ed-11e4-8e1c-c4c4248cce1e.png)

Existen estos issues relevantes [Errors verifying First IO - Learnyounode - Spoiler: Contains Solution #415](https://github.com/nodeschool/discussions/issues/415) y [my_first_io always fails, even when copying the solution verbatim #108](https://github.com/rvagg/learnyounode/issues/108) pero no logro llegar a una solución.

Any thoughts?

**Comment by nizaroni** [comment]
Hmm... yo no tuve problema. ¿Puedes pegar tu solución?

**Comment by froi** [comment]
Tengo  el código corriendo en el dir de Google Drive, no creo que tenga algo que ver pero es lo unico "raro". Este es el codigo, si lo corro con `node first_io.js <file_path>`.

``` javascript

var fs = require('fs'),
  buf,
  numLines = 0;

if (process.argv[2]) {

  buf = fs.readFileSync(process.argv[2]);

  numLines = buf.toString().match(/\n/g).length;

  console.log(numLines);

} else {

  console.error('Path to file to be parsed is missing.');

}

```

**Comment by nizaroni** [comment]
Tu solución me funcionó acá en mi máquina. Lo único que se me ocurre es lo siguiente: me ha pasado antes que yo estaba haciendo `learnyounode verify` para código de un ejercicio pero habiendo seleccionado otro ejercicio diferente en la interfaz. Haz un `learnyounode print` para confirmar que tienes seleccionado el ejercicio que es.

Fuera de eso no tengo idea! :hurtrealbad:

**Comment by froi** [comment]
Awesome. Lo intento y les dejo saber.

**Comment by gcollazo** [comment]
¿que versión de node?

**Comment by froi** [comment]
Old issue is old. I'm closing this out. 👋🏼
